version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/project:cached
    ports:
      - "3000:3000"
    tty: true
    command: bash
    init: true
