# .github\workflows\publish-dbx164lts.yml
name: publish-dbx164lts

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-lingaro-dbx164lts
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get repo owner in lowercase
        id: owner
        run: echo "GITHUB_REPOSITORY_OWNER_LOWERCASE=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute next numeric tag
        id: nexttag
        env:
          OWNER: ${{ github.repository_owner }}
          PKG: lingaro-dbx164lts
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          fetch() {
            gh api --paginate -H "Accept: application/vnd.github+json" "$1" -q '.[]?.metadata.container.tags[]?' || true
          }

          TAGS=$(fetch "orgs/${OWNER}/packages/container/${PKG}/versions?per_page=100")
          if [ -z "$TAGS" ]; then
            TAGS=$(fetch "users/${OWNER}/packages/container/${PKG}/versions?per_page=100")
          fi

          NUMS=$(printf "%s\n" $TAGS | grep -E '^[0-9]+$' || true)

          if [ -z "$NUMS" ]; then
            NEXT=1
          else
            MAX=$(printf "%s\n" $NUMS | sort -n | tail -1)
            NEXT=$((MAX + 1))
          fi

          echo "next=$NEXT" >> "$GITHUB_OUTPUT"
          echo "NEXT tag: $NEXT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: lingaro-samanta/.devcontainer/
          file: lingaro-samanta/.devcontainer/Dockerfile.dbx164lts
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.owner.outputs.GITHUB_REPOSITORY_OWNER_LOWERCASE }}/lingaro-dbx164lts:${{ steps.nexttag.outputs.next }}
            ghcr.io/${{ steps.owner.outputs.GITHUB_REPOSITORY_OWNER_LOWERCASE }}/lingaro-dbx164lts:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=lingaro-dbx164lts
            org.opencontainers.image.version=${{ steps.nexttag.outputs.next }}
          cache-from: type=gha,scope=lingaro-dbx164lts
          cache-to: type=gha,mode=max,scope=lingaro-dbx164lts,compression=zstd,compression-level=6
